### PR TITLE
58 cran comments@main [skip vbump]

### LINKED ISSUE #58: Fix CRAN issues
Please use only undirected quotation marks in the description text.
e.g. `teal` --> 'teal'

Please do not start the description with "This package", package name,
title or similar.

The Description field is intended to be a (one paragraph) description of
what the package does and why it may be useful. Please add more details
about the package functionality and implemented methods in your
Description text.

The LICENSE file is only needed if you have additional restrictions to
the license which you have not? In that case omit the file and its
reference in the DESCRIPTION file.

Please always write package names, software names and API (application
programming interface) names in single quotes in title and description.
e.g: --> 'teal'
Please note that package names are case sensitive.

\dontrun{} should only be used if the example really cannot be executed
(e.g. because of missing additional software, missing API keys, ...) by
the user. That's why wrapping examples in \dontrun{} adds the comment
("# Not run:") as a warning for the user. Does not seem necessary.
Please replace \dontrun with \donttest.

Please fix and resubmit.

### PR DESCRIPTION
**Pull request by m7pr**
Closes #58 Fixed CRAN requirements for the first CRAN submission.

### CODE REVIEW

**Comment by m7pr** [comment]
Hey @donyunardi let me know if you feel comfortable merging this PR and then pulling it locally, bumping up minor version and resubmitting to CRAN? Then, once it's accepted and released on CRAN, you would push your local changes (with version bump) to GitHub with a new tag? Or you rather have me or gogonzo doing that (the maintainer needs to accept the submission via email anyway).

**Comment by donyunardi** [comment]
We will use this PR to track CRAN feedback based on our recent process for release.

So I will:
1. Up-version the package (0.1.3)
2. Built this locally and submit to CRAN
3. git tag v0.1.3-rc# and push
4. Address any CRAN feedback and repeat steps 2 and 3 until CRAN approves.
5. Once in CRAN, then we will merge this to main and tag v0.1.3 for internal release

We probably need to block any PR to main during this time.

**Comment by donyunardi** [comment]
Package resubmitted.

**Comment by m7pr** [comment]
Hey @gogonzo did you receive an e-mail where you needed to confirm the submission?
@donyunardi wrote that he resubmitted the package on the 5th September (Tuesday), but the last date for a `incoming_pretest` build is 4th of September : P (the day you accepted the submission via e-mail on Monday)
  https://win-builder.r-project.org/incoming_pretest/

**Comment by m7pr** [comment]
@donyunardi any chance you can resubmit again? gogonzo states he didn't got a verification e-mail for your resubmission.

**Comment by donyunardi** [comment]
Package resubmitted again.
Waiting for confirmation and feedback from CRAN.

**Comment by m7pr** [comment]
@gogonzo wrote it's accepted on CRAN https://github.com/insightsengineering/teal.logger/issues/58#issuecomment-1711153561
@donyunardi we should be able to merge this and tag with `v0.1.3`

**Comment by m7pr** [comment]
@donyunardi would you be able to take it to the finish line, as my week is almost over?
I think you should put tag v0.1.3 on this branch, and once checks passes (they fail becuase we tagged the release with v0.1.3-rc1) would you be able to merge?

**Review by averissimo — APPROVED** [review]
LGTM

**Pull request merged**
